### ISSUE TITLE
Error message on https://mozilla.github.io/delivery-dashboard/#pollbot/firefox/75.0b8

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla/PollBot#254] opened 2020-03-25 16:05 UTC
The Release notes section has this error:
```
'NoneType' object has no attribute 'startswith'
```
![image](https://user-images.githubusercontent.com/454375/77558090-d6816c80-6eba-11ea-90f8-577bbd403494.png)

**Comment by mozbhearsum** [comment] 2020-03-25 20:25
I don't have enough access to properly debug this right now, but it looks like the only place we use `startswith` is: https://github.com/mozilla/PollBot/blob/master/pollbot/tasks/bedrock.py#L54

My best guess is that one of the `links` returned from https://github.com/mozilla/PollBot/blob/master/pollbot/tasks/bedrock.py#L52 is None, which may indicate an issue with the release notes page? I'm not certain.

**Comment by mozbhearsum** [comment] 2020-03-25 20:34
This is failing for older versions too, eg: https://mozilla.github.io/delivery-dashboard/#pollbot/firefox/75.0b5

So bedrock probably changed in a way that broke PollBot.

**Comment by mozbhearsum** [comment] 2020-03-25 20:59
I tried running a hacked up version of the code locally, and wasn't able to reproduce this. I'll try a few things tomorrow too, but I don't know if I can make progress on this until I can see the server side logs. I've got a bug open for that.

**Comment by mozbhearsum** [comment] 2020-03-26 15:23
I dug into this more, and I think it may be a bug in Bedrock. I opened https://github.com/mozilla/bedrock/issues/8707 for that. If that is indeed a bug, I don't think we should do anything on the Pollbot side, so we can help catch issues like this in the future.

**Comment by mozbhearsum** [comment] 2020-03-26 18:47
Bedrock pushed a fix, which looks like it will be deployed in the next few days.

**Closed by mozbhearsum** 2020-03-26 18:47 UTC
